connect 'jdbc:derby:/home/harish/Desktop/WebTech/databases/eventsdb;create=true;user=essuser;password=esspwd';

DROP TABLE "ESSUSER"."PEOPLE";
DROP TABLE "ESSUSER"."CITY";
DROP TABLE "ESSUSER"."COMMENT";
DROP TABLE "ESSUSER"."BOOKING";
DROP TABLE "ESSUSER"."EVENT";
DROP TABLE "ESSUSER"."USERS";
DROP TABLE "ESSUSER"."PHOTOS";

CREATE TABLE "ESSUSER"."USERS"
(
   ID int PRIMARY KEY NOT NULL,
   FIRSTNAME varchar(255),
   LASTNAME varchar(255),
   CITY varchar(30),
   EMAIL varchar(255),
   CONTACT varchar(255),
   ROLE varchar(3),
   POSTCODE varchar(10),
   IMAGEID int,
   CREATEDATE timestamp DEFAULT CURRENT_TIMESTAMP,
   CREATEDBY int,
   LASTMODIFIED timestamp,
   MODIFIEDBY int,
   REMARKS varchar(255),
   PASSWORD varchar(512),
   SALT varchar(64)
)
;
CREATE UNIQUE INDEX SQL140406032541660 ON "ESSUSER"."USERS"(ID)
;

CREATE TABLE "ESSUSER"."PHOTOS"
(
   ID int PRIMARY KEY NOT NULL,
   IMAGE blob(4194304),
   CREATEDATE timestamp DEFAULT CURRENT_TIMESTAMP,
   CREATEDBY int,
   LASTMODIFIED timestamp,
   MODIFIEDBY int,
   REMARKS varchar(255)
)
;
CREATE UNIQUE INDEX SQL140406032541460 ON "ESSUSER"."PHOTOS"(ID)
;

CREATE TABLE "ESSUSER"."CITY"
(
   ID int PRIMARY KEY NOT NULL,
   CITYCODE varchar(4),
   CITYNAME varchar(30),
   POSTCODE varchar(10),
   COUNTRY varchar(30),
   CREATEDATE timestamp DEFAULT CURRENT_TIMESTAMP,
   CREATEDBY int,
   LASTMODIFIED timestamp,
   MODIFIEDBY int,
   REMARKS varchar(255)
)
;
CREATE UNIQUE INDEX SQL140406032541290 ON "ESSUSER"."CITY"(ID)
;

CREATE TABLE "ESSUSER"."COMMENT"
(
   ID int PRIMARY KEY NOT NULL,
   USERID int,
   EVENTID int,
   REVIEW varchar(1024),
   CREATEDATE timestamp DEFAULT CURRENT_TIMESTAMP,
   CREATEDBY int,
   LASTMODIFIED timestamp,
   MODIFIEDBY int,
   REMARKS varchar(255)
)
;
CREATE UNIQUE INDEX SQL140406032542040 ON "ESSUSER"."COMMENT"(ID)
;

CREATE TABLE "ESSUSER"."BOOKING"
(
   ID int PRIMARY KEY NOT NULL,
   USERID int,
   EVENTID int,
   CREATEDATE timestamp DEFAULT CURRENT_TIMESTAMP,
   CREATEDBY int,
   LASTMODIFIED timestamp,
   MODIFIEDBY int,
   REMARKS varchar(255)
)
;
CREATE UNIQUE INDEX SQL140406032542230 ON "ESSUSER"."BOOKING"(ID)
;

CREATE TABLE "ESSUSER"."EVENT"
(
   ID int PRIMARY KEY NOT NULL,
   TITLE varchar(255),
   DESCRIPTION varchar(1024),
   TAGLINE varchar(255),
   LOCATION varchar(255),
   CITY varchar(30),
   STARTDATE timestamp,
   PRICE varchar(10),
   USERID int,
   IMAGEID int,
   CREATEDATE timestamp DEFAULT CURRENT_TIMESTAMP,
   CREATEDBY int,
   LASTMODIFIED timestamp,
   MODIFIEDBY int,
   REMARKS varchar(255)
)
;
CREATE UNIQUE INDEX SQL140406032541860 ON "ESSUSER"."EVENT"(ID)
;

CREATE TABLE "ESSUSER"."PEOPLE"
(
   ID int PRIMARY KEY NOT NULL,
   FORENAMES varchar(10),
   SURNAME varchar(10)
)
;
CREATE UNIQUE INDEX SQL140406032540930 ON "ESSUSER"."PEOPLE"(ID)
;
